### ISSUE TITLE
Review assignment

### ISSUE THREAD

**Issue by hchocobar** [santiagoss01/postcard#1]
# Build a Digital Postcard with HTML/CSS

## Review 

Santiago, buen trabajo!

Sin embargo hay algo a corregir para que la tarea esté totalmente correcta.

- Las propiedades `height` y `width` no soportan valores negativos y en este caso no son necesarias.
- La propiedad `width: 240px;` del selector `.body-left p:first-child` está impidiendo que el contenido se visualice correctamente dentro del post.

```css
.body-left p:first-child {
	width: 240px;
}
```
Lo demás esta muy bien, solo hace falta lograr que el post se visualice correctamente.

Ánimo y siempre hacia adelante!

**Comment by santiagoss01** [comment]
Hector Mil gracias por la corrección! no se me olvidará ya jamás no meter valores negativos por ahí en css jeje el repositorio ha sido actualizado con estos errores corregidos :)

**Comment by hchocobar** [comment]
Genial! 
Ahora si está correcto!
